# Neural Network Configuration

network:
  name: nn_model
  input_size: 11
  layers:
    - type: dense
      units: 20
      activation: relu
    - type: dense
      units: 10
      activation: relu
    - type: dense
      units: 1
      activation: relu

optimiser:
  name: SGD
  learning_rate: 0.01

loss: mse_loss

epochs: 26
batch_size: 32
